# paths
RAW_DATA_DIR:       "data/raw/"
PROCESSED_DATA_DIR: "data/processed/"
FLATTENED_DATA_DIR: "data/raw/flattened/" # contains all .nii files from RAW_DATA_DIR
SERIALIZED_MODELS:  "models/trained_models/"
METRICS_DIR:        "models/trained_history/"
ANNOTATIONS_DIR:    "data/annotations/"
CDR_DIR:            "data/tabular_data/tabular_data/CDR.csv"
GDSCALE_DIR:        "data/tabular_data/tabular_data/GDSCALE.csv"
MMSE_DIR:           "data/tabular_data/tabular_data/MMSE.csv"
MOCA_DIR:           "data/tabular_data/tabular_data/MOCA.csv"
NEUROBAT_DIR:       "data/tabular_data/tabular_data/NEUROBAT.csv"
PTDEMOG_DIR:        "data/tabular_data/tabular_data/PTDEMOG.csv"
TRAIN_LABELS_DIR:   "data/annotations/train_labels.csv"
TEST_LABELS_DIR:    "data/annotations/test_labels.csv"
PLOT_DIR_BINARY:    "reports/plots/"
SLICED_DATA_DIR:    "data/raw/slices/"

# ml_settings
MODEL: 'DenseNet121'
DEVICE: "gpu"
TRAIN_SIZE: 0.8
LEARNING_RATE: 0.001
AUTO_LEARNING_RATE: True
BATCH_SIZE: 32
AUTO_BATCH_SIZE: False #binsearch
EPOCHS: 30
NUM_WORKERS: 1 #don't set this to a higher number than train or test size
TRANSFORMER: "Crop"
CRITERION: "CrossEntropy"
OPTIMIZER: "Adam"
WANDB_USER: "brain-health"
DATA_LOADER: "slice" # "3d"

IMAGE_WIDTH: 900 # image width after cropping
IMAGE_HEIGHT: 900 # image height after cropping

IMAGE_RESIZE1: 256 # Baseline LeNet
IMAGE_RESIZE2: 256 # Baseline LeNet

# for 2d slice selection
DIMENSION: 2 # 1 = Tranversalebene, 2 = Frontalebene, 3 = Saggitalebene
NSLICE: "Center" # 'Center' or Int, selects a slice (or center slice) for given dimension


# plot settings
COLOR_SEQUENTIAL:   "bone" # matplotlib color map (used for heatmaps)
COLOR_DISCRETE:     "Paired"  # matplotlib discrete set of colors (for statistical plots:  i.e. bar plots)

# diverse
RANDOM_STATE:       "42" # what else ;)